server:
  port: 8000
spring:
  application:
    name: spring-cloud-eureka
  security:
    user:
      name: ngcly
      password: 123456
      roles: SYSTEM
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

eureka:
  instance:
    # 指定主机名 不配置会报 Batch update failure with HTTP status code 401
    hostname: localhost
  client:
    registerWithEureka: false # 是否注册自己的信息到EurekaServer，默认是true
    fetchRegistry: false # 是否拉取其它服务的信息，默认是true
    serviceUrl: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"