spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://ngcly:123456@localhost:8001}"
  boot:
    admin:
      client:
        url: http://spring-cloud-admin
  # config client 端必须用bootstrap 否则会被默认的给覆盖
  cloud:
    #消息总线
    bus:
      enabled: true
      trace:
        enabled: true

#gateway 此处必须要设为true feign才会熔断
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    health:
      show-details: always

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true