server:
  port: 8007
spring:
  application:
    name: other-service
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://ngcly:123456@localhost:8001}"

  boot:
    admin:
      client:
        url: http://spring-cloud-admin
  # zipkin 服务地址 这里使用服务名 动态获取地址
  zipkin:
    base-url: http://spring-cloud-zipkin/
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0

    #消息总线
    bus:
      enabled: true
      trace:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
feign:
  circuit-breaker:
    enabled: true
