server:
  port: 8007
spring:
  application:
    name: spring-cloud-other
  boot:
    admin:
      client:
        url: http://spring-cloud-admin
  # zipkin 服务地址 这里使用服务名 动态获取地址
  zipkin:
    base-url: http://spring-cloud-zipkin/
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  # config client 端必须用bootstrap 否则会被默认的给覆盖
  cloud:
    config:
      discovery:
        #表示使用服务发现组件的config serve，而不是自己指定的
        enabled: true
        #指定config serve的 service-id
        service-id: spring-cloud-config
      name: application-gateway,application-config
      username: ngcly
      password: 123456
      profile: dev
    #消息总线
    bus:
      enabled: true
      trace:
        enabled: true

security:
  oauth2:
    client:
      client-id: cloud_client
      access-token-uri: http://localhost:8006/oauth/token
      user-authorization-uri: http://localhost:8006/oauth/authorize
    resource:
      user-info-uri: http://localhost:8006/user/principal
      prefer-token-info: false

eureka:
  client:
    service-url:
      defaultZone: http://ngcly:123456@localhost:8000/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
feign:
  circuit-breaker:
    enabled: true
